/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include"com_example_caoxinghua_myapplication_ndk_JNIUtil.h"
/* Header for class com_example_caoxinghua_myapplication_ndk_JNIUtil */

#ifndef _Included_com_example_caoxinghua_myapplication_ndk_JNIUtil
#define _Included_com_example_caoxinghua_myapplication_ndk_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_caoxinghua_myapplication_ndk_JNIUtil
 * Method:    getWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_caoxinghua_myapplication_ndk_JNIUtil_getWorld
 (JNIEnv *env, jobject obj);
#ifdef __cplusplus
}
#endif
#endif
